import sys

with open(r'c:\Users\Lenovo\Desktop\Magnific\Magnific Projects\quotation-typescript\components\QuotationSheet.tsx', 'r', encoding='utf-8') as f:
    lines = f.readlines()

print(f'Total lines before: {len(lines)}')

# The new mobile section + UPI column replacement
# Replaces lines 648-1092 (0-indexed) = lines 649-1093 (1-indexed)
new_mobile_content = (
'                {/* Mobile Card View (Hidden on Desktop & Print) */}\n'
'                <div className="md:hidden print:hidden space-y-6 mb-8">\n'
'                    {quote.items.map((i, idx) => (\n'
'                        <div key={idx} className="bg-white border rounded-xl shadow-sm overflow-hidden">\n'
'                            <div className="flex p-4 gap-4">\n'
'                                <div className="w-21 h-24 flex-shrink-0 bg-slate-50 rounded-lg flex items-center justify-center p-4 border overflow-hidden">\n'
'                                    {(i.customImage || i.product.image) ? (\n'
'                                        <img src={i.customImage || i.product.image} className="w-full h-full object-contain" alt={i.product.name}\n'
'                                            style={i.showLineart ? { filter: \'grayscale(1) contrast(1.8) brightness(1.2)\', opacity: 0.85 } : {}} />\n'
'                                    ) : (\n'
'                                        <div className="w-full h-full flex flex-col items-center justify-center">\n'
'                                            <svg className="w-8 h-8 text-slate-300" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>\n'
'                                            <span className="text-[8px] text-slate-400 font-bold mt-1">No Image</span>\n'
'                                        </div>\n'
'                                    )}\n'
'                                </div>\n'
'                                <div className="flex-1 min-w-0">\n'
'                                    <div className="flex justify-between items-start p-4">\n'
'                                        <span className="text-[10px] bg-slate-100 text-slate-500 font-bold px-2 py-0.5 rounded uppercase tracking-wider">{i.customModelNumber || i.product.modelNumber}</span>\n'
'                                        <span className="text-xs font-bold text-slate-400">#{idx + 1}</span>\n'
'                                    </div>\n'
'                                    <h4 className="font-bold text-slate-900 text-sm mt-1 leading-tight">{i.customName || i.product.name}</h4>\n'
'                                    {!isCustomerView && (\n'
'                                        <div className="mt-3 flex flex-col space-y-2">\n'
'                                            <p className="text-[10px] text-slate-500 font-medium leading-relaxed italic border-l-2 border-indigo-200 pl-2 whitespace-pre-line">{i.customDescription || i.product.description}</p>\n'
'                                            {i.extraNote && <p className="text-[10px] text-blue-600 font-bold leading-relaxed whitespace-pre-line bg-blue-50 p-2 rounded-lg">{i.extraNote}</p>}\n'
'                                            {i.placeName && <div className="text-slate-500 italic text-[10px] pt-1 border-t border-slate-100">{i.placeName}</div>}\n'
'                                        </div>\n'
'                                    )}\n'
'                                </div>\n'
'                            </div>\n'
'                            <div className="bg-slate-50 px-4 py-3 border-t flex justify-between items-center text-xs">\n'
'                                <div className="flex flex-col">\n'
'                                    <span className="text-[10px] text-slate-400 font-bold uppercase">Qty: {i.quantity}</span>\n'
'                                    {!isCustomerView && <span className="font-medium text-slate-500 line-through text-[10px}">\u20b9{(i.customPrice !== undefined ? i.customPrice : i.product.price).toLocaleString(\'en-IN\')}</span>}\n'
'                                </div>\n'
'                                <div className="flex flex-col items-end">\n'
'                                    {(() => {\n'
'                                        const gDiscount = quote.globalDiscountValue || 0;\n'
'                                        const basePrice = i.customPrice !== undefined ? i.customPrice : i.product.price;\n'
'                                        const effectivePrice = i.includeGst !== false ? basePrice : basePrice / 1.18;\n'
'                                        const appliesDisc = i.product.category !== \'Services\' && i.includeDiscount !== false;\n'
'                                        const discountedPrice = (quote.globalDiscountType && gDiscount > 0 && appliesDisc) ? effectivePrice * (1 - gDiscount / 100) : effectivePrice;\n'
'                                        return (\n'
'                                            <div className="flex flex-col items-end">\n'
'                                                <span className="font-black text-indigo-700 text-base">\u20b9{Math.round(discountedPrice * i.quantity).toLocaleString(\'en-IN\')}</span>\n'
'                                                {i.includeDiscount === false && i.product.category !== \'Services\' && (\n'
'                                                    <span className="text-[9px] text-red-600 font-bold uppercase mt-0.5 leading-none px-1 py-0.5 bg-red-50 rounded print:hidden">Disc Off</span>\n'
'                                                )}\n'
'                                            </div>\n'
'                                        );\n'
'                                    })()}\n'
'                                </div>\n'
'                            </div>\n'
'                        </div>\n'
'                    ))}\n'
'\n'
'                    {/* Mobile Summary Rows */}\n'
'                    {summaryRows.length > 0 && (\n'
'                        <div className="bg-slate-800 text-white rounded-xl p-4 space-y-2 text-xs">\n'
'                            {summaryRows.map(row => (\n'
'                                <div key={row.id} className="flex justify-between items-center">\n'
'                                    <span style={{ color: row.color || \'#cbd5e1\', fontWeight: row.bold ? 900 : row.thin ? 300 : 600 }} className="uppercase tracking-wide text-[10px]">\n'
'                                        {row.label || \'\u2014\'}\n'
'                                    </span>\n'
'                                    <span style={{ color: row.color || \'#ffffff\', fontWeight: row.bold ? 900 : row.thin ? 300 : 700 }} className="text-sm">\n'
'                                        {row.value || \'\u2014\'}\n'
'                                    </span>\n'
'                                </div>\n'
'                            ))}\n'
'                        </div>\n'
'                    )}\n'
'                </div>\n'
'\n'
'                <div className="mt-6 pt-4 border-t border-slate-200 print-compact print:mt-1 print:pt-1">\n'
'                    <div className="flex flex-col gap-6 print:gap-3">\n'
'                        {/* Banking Details & UPI QR */}\n'
'                        <div className="flex flex-col md:flex-row print:flex-row gap-12 items-start justify-between no-print-break w-full">\n'
'                            {/* Banking Column */}\n'
'                            <div className="flex-1 flex flex-col items-start">\n'
'                                <h4 className="text-[10px] font-black text-indigo-700 border-b-2 border-indigo-700 pb-2 mb-4 uppercase tracking-[0.2em] w-full text-left">Banking Details (RTGS / NEFT)</h4>\n'
'                                <div className="space-y-3">\n'
'                                    <div className="flex items-center text-[10px]">\n'
'                                        <span className="w-28 font-black text-slate-500 uppercase tracking-widest leading-none">Company Name</span>\n'
'                                        <span className="font-bold text-slate-900 uppercase leading-none">Magnific Home Appliances</span>\n'
'                                    </div>\n'
'                                    <div className="flex items-center text-[10px]">\n'
'                                        <span className="w-28 font-black text-slate-500 uppercase tracking-widest leading-none">Bank &amp; Branch</span>\n'
'                                        <span className="font-bold text-slate-900 uppercase leading-none">Axis Bank Gottigere </span>\n'
'                                    </div>\n'
'                                    <div className="flex items-center text-[10px]">\n'
'                                        <span className="w-28 font-black text-slate-500 uppercase tracking-widest leading-none">A/c No</span>\n'
'                                        <span className="font-black text-indigo-700 tracking-wider text-xs leading-none">926030005650178</span>\n'
'                                    </div>\n'
'                                    <div className="flex items-center text-[10px]">\n'
'                                        <span className="w-28 font-black text-slate-500 uppercase tracking-widest leading-none">IFSC Code</span>\n'
'                                        <span className="font-black text-indigo-700 tracking-[0.2em] text-xs uppercase leading-none">UTIB0004071</span>\n'
'                                    </div>\n'
'                                </div>\n'
'                            </div>\n'
'\n'
'                            {/* UPI Column */}\n'
'                            <div className="w-full md:w-56 print:w-48 flex-shrink-0 flex flex-col items-start">\n'
'                                <h4 className="text-[10px] font-black text-indigo-700 border-b-2 border-indigo-700 pb-2 mb-4 uppercase tracking-[0.2em] w-full text-left">Secure UPI Payment</h4>\n'
'                                <div className="text-left w-full flex flex-col items-start">\n'
'                                    <UPIScanner\n'
'                                        amount={0}\n'
"                                        quotationId={quote.id || 'NEW'}\n"
'                                        customerName={quote.customer.name}\n'
'                                    />\n'
'                                </div>\n'
)

# Lines 1-648 (indices 0-647) stay (the first 648 lines)
# Lines 649-1093 (indices 648-1092) are replaced
# Lines 1094+ (indices 1093+) stay

new_lines = lines[:648] + [new_mobile_content] + lines[1093:]

with open(r'c:\Users\Lenovo\Desktop\Magnific\Magnific Projects\quotation-typescript\components\QuotationSheet.tsx', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f'Done.')
